# Base image
FROM node:14-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Set environment variable for development
ENV REACT_APP_ENV development

# Expose port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
